[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "deteccion_fraude"
version = "0.0.1"
description = "Deteccion de fraude en transacciones."
authors = [
  { name = "grupo_2" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"

[project.scripts]
fraude = "deteccion_fraude.modeling.train:app"


[tool.ruff]
line-length = 99
src = ["deteccion_fraude"]
include = ["pyproject.toml", "deteccion_fraude/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["deteccion_fraude"]
force-sort-within-sections = true

